[build]
command = "npm run build"
publish = "./dist/public"
node_compat = true

[build.environment]
NODE_VERSION = "18.18.0"

# Production environment settings
[env.production]
name = "portfolio-production"

# Enable caching for better performance
[cache]
caching = true
browser_TTL = 3600
serve_stale = true
