[build]
command = "npm run build"
publish = "dist"
node_compat = true

[build.environment]
NODE_VERSION = "18.18.0"

[site]
bucket = "./dist"

[env.production]
name = "portfolio-production"

# Optional: Enable caching for better performance
[cache]
caching = true
browser_TTL = 3600
serve_stale = true
